 const users=[
  {
    id: 1,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/316400/316486.png",
    imageUrl2: "https://thedailyguardian.com/wp-content/uploads/2020/04/Sachin-Emotion.jpg",
    imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStrEiebmQS7oYKtedAMQ8zpliU7aToUE8-yQ&s",
    nickname: 'Tendlya, Little Master',
    born: 'April 24, 1973, Bombay (now Mumbai), Maharashtra',
    fullName: 'Sachin Ramesh Tendulkar',
    name: 'Sachin Tendulkar',
    battingstyle: 'Right hand Bat',
    team: 'India',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Top order Batter',
    about:' Sachin Tendulkar was the most complete batter of his time, the most prolific run-maker of all time, and arguably the biggest cricket icon the game has ever known.'
  },
  {
    id: 2,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/316600/316605.png",
    imageUrl2: "https://cdn.britannica.com/48/252748-050-C514EFDB/Virat-Kohli-India-celebrates-50th-century-Cricket-November-15-2023.jpg",
    imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZrGFcgaYo_EWTABQpI0A-fyQCcqiRf5Ix9Q&s",
    nickname: 'Cheeku',
    born: 'November 05, 1988, Delhi',
    fullName: 'Virat Kohli',
    name: 'Virat Kohli',
    battingstyle: 'Right hand Bat',
    team: 'India',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Top order Batter',
    about:' India has given to the world many a great cricketer but perhaps none as ambitious as Virat Kohli. To meet his ambition, Kohli employed the technical assiduousness of Sachin Tendulkar and fitness that was in the league of top athletes in the world, not just cricketers. As a result, Kohli became the most consistent all-format accumulator of his time, making jaw-dropping chases look easy, and finding, in his own words, the safest possible way to score runs. Plenty of them. '
  }, 
  {
    id: 3,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/319900/319946.png",
    imageUrl2: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSTfwnS8DtN2mJtyTe-eu_g2eVF0MhPxd1Su32H3mgRNrl48zIuShXc5ULBMXGIxFeXMOUefPZ_D0_QNpKTiHKf7VUouYwKAHuQX_t5-Q",
    imageUrl3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOH9V1twT5BO2vd4djqJe2qBJC3WVpj8A8UA&s",
    nickname: 'Mahi, Thala',
    born: 'July 07, 1981, Ranchi, Bihar (now Jharkhand)',
    fullName: 'Mahendra Singh Dhoni',
    name: 'MS Dhoni',
    battingstyle: 'Right hand Bat',
    team: 'India',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Wicketkeeper Batter',
    about:' MS Dhoni led India to three ICC titles but he is nearly as famous for his exploits in the yellow of Chennai Super Kings in the Indian Premier League.Dhoni, known as CSKs "Thala (leader) captained the franchise to ten finals in their first 14 IPL seasons and won them five titles - in 2010, 2011, 2018, 2021 and 2023 . He is led them to the playoffs in 12 editions, making them the most consistent team in the IPL. In a surprise move on the eve of the IPL 2024 season opener, Dhoni stepped down as CSK captain and was succeeded by Ruturaj Gaikwad.'  
  },
  {
    id: 4,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/331100/331193.png",
    imageUrl2: "https://randomuser.me/api/portraits/med/men/75.jpg",
    imageUrl3: "https://randomuser.me/api/portraits/med/men/75.jpg",
    nickname: 'Harleen',
    born: 'June 21, 1998, Chandigarh',
    fullName: 'Harleen Deol',
    name: 'Harleen Deol',
    battingstyle: 'Right hand Bat',
    team: 'India',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Middle order Batter',
    about:' Harleen Kaur Deol (born 21 June 1998) is an Indian cricketer. She plays for Himachal Pradesh as an attacking right-hand batter who also occasionally bowls right arm leg spin.Harleen made her Womens One Day International (WODI) debut for India against England on 22 February 2019, at Wankhede in Mumbai,[3] becoming the second woman cricketer from Chandigarh to play for India after Taniya Bhatia.[4] She completed her schooling from Yadavindra Public School, Mohali[5] and subsequently made her Womens Twenty20 International (WT20I) debut against England on 4 March 2019' 
   },
  {
    id: 5,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/320600/320632.png",
    imageUrl2: "https://img.naidunia.com/naidunia/ndnimg/17072023/17_07_2023-smritimandhanabirthday.jpg",
    imageUrl3: "https://dwz6kul9y5yls.cloudfront.net/youth/wp-content/uploads/2022/07/card_smriti_india.jpg",
    nickname: 'Smriti',
    born: 'July 18, 1996, Bombay (now Mumbai), Maharashtra',
    fullName: 'Smriti Shriniwas Mandhana',
    name: 'Smriti Mandhana',
    battingstyle: 'Left hand Bat',
    team: 'India',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Opening Batter',
    about:' Smriti Shriniwas Mandhana (smrɪti mɑndanɑ born 18 July 1996) is an Indian cricketer who represents the Indian womens national team. She plays for Royal Challengers Bangalore in the Womens Premier League (WPL).[2][3][4] In domestic cricket, she represents the Maharashtra cricket team.[4]'  
  },
  {
    id: 6,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/319900/319955.png",
    imageUrl2: "https://images.firstpost.com/uploads/2024/04/Yuzvendra-Chahal2-2024-04-dd24d88bba149fa8bb064f4455e51d66-1200x675.jpg?im=FitAndFill=(596,336)",
    imageUrl3: "https://c.ndtvimg.com/2023-08/aup1ebbo_yuzvendra-chahal-afp_625x300_06_August_23.jpg?im=FeatureCrop,algorithm=dnn,width=806,height=605",
    nickname: 'Yuzvi',
    born: 'July 23, 1990, Jind, Haryana',
    fullName: 'Yuzvendra Singh Chahal',
    name: 'Yuzvendra Chahal',
    battingstyle: 'Right hand Bat',
    team: 'India',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Bowler',
    about:'Yuzvendra Chahal is an attacking legspinner who first attracted attention when he took 34 wickets in the National Under-19 Cooch Behar Trophy in 2009, ending the tournament as its leading wicket-taker. A former chess player who represented India at junior levels, Chahal made his first-class debut for Haryana the same year and was signed by Mumbai Indians in 2011 to be part of their IPL squad.'
    
    
    },
  {
    id: 7,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/316600/316692.png",
    imageUrl2: "https://media.assettype.com/freepressjournal/2024-05/b9178e67-7432-4ef1-85a2-4adfb20af6f1/Pat%20Cummins%204.jpg",
    imageUrl3: "https://media.assettype.com/freepressjournal/2024-05/b9178e67-7432-4ef1-85a2-4adfb20af6f1/Pat%20Cummins%204.jpg",
    nickname: 'Cummo',
    born: 'May 08, 1993, Westmead, Sydney',
    fullName: 'Patrick James Cummins',
    battingstyle: 'Right hand Bat',
    team: 'Australia',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Right arm Fast Bowler',
    about:' Earmarked as a potential star from a young age, Pat Cummins made his Test debut as an 18-year-old but had to wait six years for his next appearance as injuries struck a body that could not withstand the workload. The bowler who emerged in 2017 was a thoroughbred quick who became one of the standout players in the world and, in late 2021, Australias Test captain in dramatic circumstances. By 2023 he had led the team to the World Test Championship and ODI World Cup.'
    },
  {
    id: 8,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/373900/373914.png",
    imageUrl2: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_800,q_50/lsci/db/PICTURES/CMS/375500/375575.jpg",
    imageUrl3: "https://alchetron.com/cdn/kim-garth-802d4c22-9a1c-40c5-89a6-95f04918528-resize-750.jpeg",
    nickname: 'Kim',
    born: 'April 25, 1996, Dublin',
    fullName: 'Kimberley Jennifer Garth',
    name: 'Kimberley Garth',
    battingstyle: 'Right hand Bat',
    team: 'Australia',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Allrounder',
    about:' Kimberley Jennifer Garth (born 25 April 1996) is an Irish-Australian cricketer who currently plays for Victoria, Melbourne Stars and Australia. An all-rounder, she plays as a right-arm medium bowler and right-handed batter. Between 2010 and 2019, she played international cricket for Ireland, the country of her birth, playing more than 100 matches for the side, before deciding to move to Australia.[1] She made her international debut for Australia in December 2022.'  
  },
  {
    id: 9,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/322200/322250.png",
    imageUrl2: "https://www.hindustantimes.com/ht-img/img/2024/04/01/550x309/CRICKET-NZL-PAK-T20-45_1711959419851_1711959444139.jpg",
    imageUrl3: "https://i.brecorder.com/primary/2022/12/63a1ba6acc435.jpg",
    nickname: 'Shaheen',
    born: 'April 06, 2000, Khyber Agency',
    fullName: 'Shaheen Shah Afridi',
    name: 'Shaheen Afridi',
    battingstyle: 'Right hand Bat',
    team: 'Pakistan',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Left arm Fast Bowler',
    about:' A baby face perched on a two-metre body, Shaheen Afridis story is trademark Pakistani. An 18-year old already comfortable in the green shirt of the national side, he has been on the radar of the national selectors for almost three years. In a more intimate circle, he was destined for great achievements well before his teenage years, with an international cricketer for an elder brother.' 
   },
  {
    id: 10,
    imageUrl: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_640,q_50/lsci/db/PICTURES/CMS/335100/335136.png",
    imageUrl2: "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_480,q_50/lsci/db/PICTURES/CMS/342100/342102.10.jpg",
    imageUrl3: "https://images.icc-cricket.com/image/upload/t_ratio16_9-size50/prd/dwspspmkyhdcdazuesb0",
    nickname: 'wami',
    born: 'August 22, 2005',
    fullName: 'Rajapaksha Mudiyanselage Vishmi',
    name: 'Rajapaksha Vishmi',
    battingstyle: 'Right hand Bat',
    team: 'Srilanka',
    address: '123 MG Road, Kochi, Kerala, India',
    role: 'Top order Batter',
    about:' Rajapaksha Mudiyanselage Vishmi Dewmini Gunarathne is a Sri Lankan cricketer who currently plays for Chilaw Marians Cricket Club and Sri Lanka. She plays as a right-handed batter.'  }
];

module.exports = users;